name: build

on:
  push:
    # tag based deployment to use a single trunk branch which is easier to maintain long-term
    tags:
      - dev-app*
      - qa-app*
      - release-app*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (for multi-platform builds if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/<github-role-name>

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    # Build Docker image
    - name: Build Docker image
      env:
        APP_DSN: ${{ secrets.RDS_CONNECTION_STRING }}
      run: |
        docker build -f ./go_app/cmd/Dockerfile -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/interview-go-app:${{ github.sha }} .

    # Push Docker image to Amazon ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/interview-go-app:${{ github.sha }}

    # Set up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # Configure kubectl to use your EKS cluster
    - name: Set up kubectl for EKS
      uses: eks-actions/eks-kubeconfig-action@v1
      with:
        cluster_name: ${{ secrets.CLUSTER_NAME }}
        region: ${{ secrets.AWS_REGION }}

    # Deploy using Helm
    - name: Deploy via Helm
      run: |
        helm upgrade --install interview-go-app ./go_app/helm/interview-go-app --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/interview-go-app,image.tag=${{ github.sha }} --namespace interview-go-app --create-namespace
